apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: 
  name: springboot-products-svc
  labels:
        app: springboot-products-api
        tier: service-api
spec:
  ports:
    - protocol: "TCP"
      targetPort: 8080  # The port exposed by the service
      port: 8080  # The port on which the service is running on in the cluster
      
  type: LoadBalancer # service Type
  selector:
    app: springboot-products-api