# Deployment of mysql of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-api 
    tier: database
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysql-api
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # It should match Service and Deployment selectors
        app: mysql-api
        tier: database
    spec:
      containers:
        - image: mysql:8.0.33 # docker hub image
          args:
            - "--ignore-db-dir=lost+found" 
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets  # From secret YAML
                  key :  password

            - name: MYSQL_DATABASE 
              valueFrom :
                configMapKeyRef :
                  name : db-config      # From congifMap YAML
                  key :  dbName


          ports:
            - containerPort: 3306
              name: mysql-pv
          volumeMounts:       # Mounting voulume obtained from Persistent Volume Claim
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql 
            
      volumes:
        - name: mysql-persistent-storage 
          persistentVolumeClaim:
            claimName: mysql-pv-claim
       
